### PR TITLE
fix for bug #65, stopping auto complete on hex inputs

### PR DESCRIPTION
**Pull request by runrog**
Fix for https://github.com/xiaokaike/vue-color/issues/65

### CODE REVIEW

**Comment by 304NotModified** [comment]
:+1:

**Comment by 304NotModified** [comment]
@xiaokaike any release planned?

**Comment by xiaokaike** [comment]
@304NotModified  is release

**Comment by 304NotModified** [comment]
Ah, I was checking https://github.com/xiaokaike/vue-color/releases

Added a badge to make the latest version more clear: https://github.com/xiaokaike/vue-color/pull/72

**Pull request merged**
