### PR TITLE
Fixed Bug #35

### PR DESCRIPTION
**Pull request by Daniesy**
See bug #35

### CODE REVIEW

**Comment by Daniesy** [comment]
@xiaokaike please bump the version so we can fetch the update with npm

**Comment by thisBomBomBom** [comment]
@xiaokaike please update version,thanks.

**Comment by xiaokaike** [comment]
update

**Comment by m00nk** [comment]
Please, rebuild the final JS files (in /dist folder). Thank you.

**Comment by xiaokaike** [comment]
sorry  forget rebuild

**Comment by m00nk** [comment]
Now all is ok, thank you :+1:

**Pull request merged**
